import type { NextPage } from 'next'
import {useState} from 'react'
import Head from 'next/head'
import Image from 'next/image'
import Searchbar from '../components/Searchbar'
import { products } from '../Data/products'
import { GetServerSideProps } from 'next'
import { ProductInterface } from '../Data/ProductInterface'
import styles from '../styles/Home.module.css'
import List from '../components/List'

interface HomeProps{
  products: ProductInterface[]
}

const Home = ({products}: HomeProps) => {

  const [filteredProducts, setFilteredProducts] = useState<ProductInterface []>(products);
  const [activeCategory, setActive] = useState('all')

  const filter =(str: string)=>{
      setFilteredProducts(products.filter(item=>item.brandName.toLowerCase().includes(str.toLowerCase())))
  }

  const categoryFilter = (category: string)=>{
    if(category === 'all'){
      setFilteredProducts(products)
    }else{
      setFilteredProducts(products.filter(item=>item.type === category))
    }
    
  }

  const setActiveCat = (cat: string)=>{
    setActive(cat)
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Pharmarcy UI</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
         <Searchbar filter={filter} setActiveCat={setActiveCat} />
         <List products={filteredProducts} categoryFilter={categoryFilter} active={activeCategory} setActiveCat={setActiveCat} />
      </main>
    </div>
  )
}

export const getServerSideProps: GetServerSideProps = async (ctx)=>{
  return{
    props: {
      products: products
    }
  }
}

export default Home
